version: '3.6'

services:
  gitlab:
    image: 'gitlab/gitlab-ee:latest'

    hostname: 'gitlab.local.dev'

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.local.dev'
        nginx['listen_port'] = 80
        nginx['listen_https'] = false
        nginx['proxy_set_headers'] = {
          'X-Forwarded-Proto' => 'https',
          'X-Forwarded-Ssl' => 'on'
        }
        gitlab_rails['gitlab_shell_ssh_port'] = 2222
        gitlab_rails['smtp_enable'] = true
        gitlab_rails['smtp_address'] = "mailhog"
        gitlab_rails['smtp_port'] = 1025
        gitlab_rails['smtp_user_name'] = "mailhog"
        gitlab_rails['smtp_password'] = "mailhog"
        gitlab_rails['smtp_domain'] = "packagist.com.lo"
        gitlab_rails['smtp_authentication'] = "login"
        gitlab_rails['smtp_enable_starttls_auto'] = false
        gitlab_rails['smtp_openssl_verify_mode'] = 'none'

    extra_hosts:
      - "gitlab.local.dev:host-gateway"

    ports:
      - '2280:80'
      - '2222:22'

    volumes:
      - './config:/etc/gitlab'
      - './logs:/var/log/gitlab'
      - './data:/var/opt/gitlab'

    shm_size: '256m'

  mailhog:
    image: "mailhog/mailhog"

    ports:
      - "8025:8025"